name: Render quarto website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  render_site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install GDebi first
      run: sudo apt-get install gdebi-core
    - name: Download the deb file
      run: sudo curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb 
    - name: Install the deb file
      run: sudo apt-get install -y ./quarto-linux-amd64.deb
    - name: Verify Install
      run: /usr/local/bin/quarto check
    - name: Install quarto deps
      run: pip install nbformat nbclient ipykernel jupyter tomli biopython scholarly crossrefapi toml pymongo orcid
    - name: Install academicdb
      run: pip install academicdb
    - name: decrypt config file
      run: ./decrypt_secret.sh
      continue-on-error: true
      env:
        CONFIG_SECRET_PASSPHRASE: ${{ secrets.CONFIG_SECRET_PASSPHRASE }}
    - name: decrypt pybliometrics config file
      run: ./decrypt_pyb_config.sh
      continue-on-error: true
      env:
        TOKEN_PASSCODE: ${{ secrets.TOKEN_PASSCODE }}
    - name: build site
      run: quarto render .
      env:
        # Only enabled on pull requests
        POLDRACKLAB_IGNORE_FAILURE: $GITHUB_BASE_REF
    - name: Deploy
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs # The folder the action should deploy.
